import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-theme="halloween">
        <button className="btn btn-primary">Primary</button>
      </main>
    </>
  );
}
